default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: truong295
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: api-sample

test:
  <<: *default
  database: api-sample

production:
  <<: *default
  database: api-sample
  username: api-sample
  password: <%= ENV['foods_and_drinks_DATABASE_PASSWORD'] %>
